### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by Cartrigger** [QuestCraftPlusPlus/Pojlib#12]
i download but no apk

**Comment by Cartrigger** [comment]
Pls help

**Comment by TecEash1** [comment]
Apk vanish pojav library bam

Hope that helps! :)

**Comment by JaffaJace** [comment]
Factory reset, should fix your issue!

**Comment by Cartrigger** [comment]
it didn't fix my quest is now on fire

**Comment by Cartrigger** [comment]
🧇

**Comment by JaffaJace** [comment]
Dont worry thats intentional, game should load after 2.9 sextillion years

**Comment by JaffaJace** [comment]
Enjoy playing QuestNite!
