### ISSUE TITLE
Pojlib documentation?

### ISSUE THREAD

**Issue by BurAndBY** [QuestCraftPlusPlus/Pojlib#17]
Is there any Pojlib documentation? If no, is there any open-source project based on it?

**Comment by KendrickLamar2003** [comment]
Pojlib is based on PojavLauncher, so you might want to go there for documentation.

**Comment by CADIndie** [comment]
We have added JavaDoc comments inside of Pojlib however you should be able to get by mostly with just looking at the API class (API_V1).
